name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create virtualenv
        run: |
          which python
          python -m venv venv
          source venv/bin/activate
          python -m pip install --constraint=.github/workflows/constraints.txt --upgrade pip
          which python

      - name: Set up Poetry cache
        uses: actions/cache@v3.3.1
        with:
          path: venv
          key: venv-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}

      - name: Install Poetry and Python dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version
          poetry config virtualenvs.in-project true
          poetry config virtualenvs.create false
          poetry config virtualenvs.path venv
          source venv/bin/activate
          which python
          poetry install --no-root
